### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by helpermethod** [kevincharm/parcel-plugin-web-extension#3]
Hi Kevin,

first of all great work, thank you very much!

I'm trying to use the plugin with a WebExtension of mine but I'm getting the following error

```js
> parcel build src/manifest.json

🚨  Cannot find module 'parcel/src/Asset'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (/Users/oliver.weiler/git/meinestadt-devtools/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/oliver.weiler/git/meinestadt-devtools/node_modules/parcel-plugin-web-extension/src/ManifestAsset.js:2:15)
    at Module._compile (/Users/oliver.weiler/git/meinestadt-devtools/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

It seems not all files referenced in the manifest are found. 
It would be awesome if the plugin could emit a more useful error message which tells you which file is missing.

**Comment by kevincharm** [comment]
Hi @helpermethod! I believe this is related to #1, I had the incorrect dependency. Please give v1.1.0 a try :)

**Comment by helpermethod** [comment]
Hi @kevincharm,

the update resolved the issue, thank you very much! Just ported my WebExtension from Webpack to Parcel + Parcel-Plugin-Web-Extension and everything works out of the box!
